/* Writes dist/sw.js with a precache list of whatever the build actually produced.
   Run after `vite build` — the asset filenames are content-hashed, so the list
   (and therefore the cache name) changes exactly when the app changes. */
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const dist = path.join(__dirname, "..", "dist");
const BASE = "/moto/";

function walk(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
}

// The whole build is a few hundred kB, so precache all of it rather than
// guessing which icons the OS will ask for.
const files = walk(dist)
  .map(p => path.relative(dist, p).split(path.sep).join("/"))
  .filter(f => f !== "sw.js");

const urls = ["./", ...files.map(f => "./" + f)];
const version = crypto.createHash("sha1")
  .update(files.map(f => f + fs.statSync(path.join(dist, f)).size).join("|"))
  .digest("hex").slice(0, 12);

const sw = `/* Moto Log service worker — generated by tools/make-sw.cjs. Do not edit. */
const CACHE = "moto-log-${version}";
const PRECACHE = ${JSON.stringify(urls, null, 2)};

self.addEventListener("install", event => {
  event.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE)));
  // Still no automatic skipWaiting — a build must not reload the page while you
  // are part-way through an entry. But the page can now ask us to take over, so
  // an update is one tap away instead of depending on every instance being
  // closed, which is easy to get wrong on a phone.
});

self.addEventListener("message", event => {
  if (event.data === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("activate", event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener("fetch", event => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;

  // Navigations always resolve to the app shell, so a deep link or a shortcut
  // still opens offline.
  if (req.mode === "navigate") {
    event.respondWith((async () => {
      const cached = await caches.match("${BASE}", { ignoreSearch: true });
      if (cached) return cached;
      try { return await fetch(req); }
      catch { return new Response("Offline", { status: 503, headers: { "Content-Type": "text/plain" } }); }
    })());
    return;
  }

  // Everything else is content-hashed, so cache-first is safe.
  event.respondWith((async () => {
    const cached = await caches.match(req);
    if (cached) return cached;
    try {
      const res = await fetch(req);
      if (res.ok && res.type === "basic") {
        const clone = res.clone();
        caches.open(CACHE).then(c => c.put(req, clone));
      }
      return res;
    } catch (err) {
      return cached || Response.error();
    }
  })());
});
`;

fs.writeFileSync(path.join(dist, "sw.js"), sw);
console.log(`sw.js written — cache moto-log-${version}, ${urls.length} precached:`);
urls.forEach(u => console.log("   " + u));
